fixed styling of author link on category page
aemsites/sling pull request #150
Opened 2024-07-16 08:56 UTC by rusmeenkhan1

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #144 

Test URLs:
- Before: https://main--sling--aemsites.aem.page/whatson/movies
- After: https://144-link-to-authorpage--sling--aemsites.aem.page/whatson/movies

home & food
Test URLs:
- Before: https://main--sling--aemsites.aem.page/whatson/entertainment/home-and-food
- After: https://144-link-to-authorpage--sling--aemsites.aem.page/whatson/entertainment/home-and-food

2024-07-16 09:25 UTC, rusmeenkhan1 commented
Hi Team, i saw previously it was showing some contrast warnign with the older link-color. So i have updated it to a nearby matching color to avoid contrast warning. 
<img width="1521" alt="Screenshot 2024-07-16 at 2 48 25 PM" src="https://github.com/user-attachments/assets/a6f18033-5425-4efa-9fb0-f36752329091">

I have chosed below color:
![Uploading Screenshot 2024-07-16 at 2.54.56 PM.png…]()

2024-07-16 10:16 UTC, helms-charity commented on aemedge/blocks/category/category.css
> +  text-decoration: underline;
Only underline if the name is linked (currently it is not).

2024-07-16 10:17 UTC, helms-charity requested changes
The styling looks good, but should only look like links when the names are linked.

2024-07-19 12:58 UTC, helms-charity approved these changes
Looks good

2024-07-19 12:58 UTC, merged