fixed buttons size
aemsites/sling pull request #414
Opened 2024-11-08 13:43 UTC by rusmeenkhan1

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #391 

Test URLs:
- Before: https://main--sling--aemsites.aem.live/
- After: https://391-buttons--sling--aemsites.aem.live/

2024-11-08 15:33 UTC, rusmeenkhan1 commented
Still WIP.

2024-11-08 15:59 UTC, helms-charity requested changes
The buttons shouldn't have a min-width I don't think. Compare to their site, https://www.sling.com/#freestream 
And they still have too much padding around the text.

2024-11-08 21:49 UTC, helms-charity commented
Ouch I realized where we are already using bold.  Links that are within other text should NOT be given the button-container class.
![image](https://github.com/user-attachments/assets/aee95239-2559-491e-8af1-09b538024279)

2024-11-11 04:26 UTC, rusmeenkhan1 commented
Yes Charity, i also noticed this.

2024-11-11 13:54 UTC, helms-charity reviewed
I'm not seeing a black button for AMC+ on the page linked in this ticket, https://391-buttons--sling--aemsites.aem.page/

2024-11-11 14:44 UTC, helms-charity approved these changes
I think this looks good now

2024-11-20 14:22 UTC, helms-charity commented on aemedge/styles/styles.css
>    font-size: 1rem;
Live site has font size of 18px for buttons; use this REM size (or if we have a variable for it
`font-size: 1.125rem;`

2024-11-21 11:21 UTC, helms-charity commented on aemedge/styles/styles.css
> +  font-size: 1.25rem;
Should be 1.125

2024-11-21 11:39 UTC, merged