Issue 208: created new block for offer cards
aemsites/sling pull request #476
Opened 2024-12-31 18:43 UTC by neetunegi

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix # 208 

Test URLs:
- Before: https://main--sling--aemsites.aem.live/
- After: https://issue208--sling--aemsites.aem.page/drafts/neetu/offer-cards

2025-01-02 16:02 UTC, helms-charity commented
Do you want to match the design for desktop and mobile?
![image](https://github.com/user-attachments/assets/ba2c4279-5072-4436-bcca-e7a599dee6f6)

![image](https://github.com/user-attachments/assets/81b6d5f3-ae47-4bdf-a3f2-bc864888fa37)

2025-01-06 20:40 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.js
> +  const mediaDIV = createTag('div', { class: 'foreground-container' });
There isn't a foreground section of your block, right?

2025-01-06 20:50 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.js
> +  const mediaDIV = createTag('div', { class: 'foreground-container' });
checking on it

2025-01-06 20:56 UTC, helms-charity commented
@neetunegi you will need to only let those offer card blocks display as flex within the same section, not any other content such as headlines. See your test page - I added 2 additional sections with 2 and 1 card.

2025-01-06 20:56 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.js
> +  const mediaDIV = createTag('div', { class: 'foreground-container' });
removed the foreground related code

2025-01-06 21:39 UTC, neetunegi commented
> @neetunegi you will need to only let those offer card blocks display as flex within the same section, not any other content such as headlines. See your test page - I added 2 additional sections with 2 and 1 card.

checking.

2025-01-06 22:15 UTC, neetunegi commented
> > @neetunegi you will need to only let those offer card blocks display as flex within the same section, not any other content such as headlines. See your test page - I added 2 additional sections with 2 and 1 card.
> 
> checking.

@helms-charity I am trying with below but i am not sure if this will be good or still can be done with better way.
.section.offer-cards-container{
        display: flex;
        flex-wrap: wrap;
        max-width: fit-content;
        margin-left: auto;
        margin-right: auto;
    }

    .offer-cards-container>div:not(.offer-cards-wrapper)
    {
        display: block;
        width:100%
    }

    .section.offer-cards-container>div.offer-cards-wrapper{
        padding: 5px;
    }

2025-01-06 22:16 UTC, neetunegi commented
> > > @neetunegi you will need to only let those offer card blocks display as flex within the same section, not any other content such as headlines. See your test page - I added 2 additional sections with 2 and 1 card.
> > 
> > 
> > checking.
> 
> @helms-charity I am trying with below but i am not sure if this will be good or still can be done with better way. .section.offer-cards-container{ display: flex; flex-wrap: wrap; max-width: fit-content; margin-left: auto; margin-right: auto; }
> 
> ```
> .offer-cards-container>div:not(.offer-cards-wrapper)
> {
>     display: block;
>     width:100%
> }
> 
> .section.offer-cards-container>div.offer-cards-wrapper{
>     padding: 5px;
> }
> ```

![image](https://github.com/user-attachments/assets/6c3b3542-8c6a-47ac-8fff-82ef60000856)

2025-01-07 17:58 UTC, neetunegi commented
@helms-charity any feedback on this? whenever you will be able to check please

2025-01-07 18:02 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        margin-right: auto;
add this after line 146:
`justify-content: center;`

2025-01-07 18:09 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        margin-right: auto;
You are making good progress on the layout. The component demo page says "Image size for all devices: 373 x 224 px", so yours is too large. For mobile, you still need to hide the bullets.

![image](https://github.com/user-attachments/assets/220bd09b-8642-4278-90a8-f7fe5af37bbe)

2025-01-07 18:37 UTC, neetunegi commented
@helms-charity I am checking on image size but bullets are hiding on mobile , can you please refresh the page 
![image](https://github.com/user-attachments/assets/3f5f7eff-19a5-4574-b426-7f6b697514f9)

2025-01-08 18:52 UTC, neetunegi commented
@helms-charity , I updated some css to correct the image, but i am still trying to see how gradient would work on whole card. I tried few things not successful yet on them but here i am uploading the image size to tell you image size 
![image](https://github.com/user-attachments/assets/54602814-0f04-42c7-bc4a-e11f506695d5)

2025-01-09 21:27 UTC, neetunegi commented
@helms-charity  pushed fixes. please review

2025-01-09 21:37 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-height: 566px;
you can remove this min-height since you have it at line 144

2025-01-09 21:38 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-height: 566px;
Change to 366

2025-01-09 21:40 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        padding: 5px;
add "display: flex;" here so that they will all be the same height when there is more than 1.

2025-01-09 21:41 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-height: 566px;
Change this to 366px so it isn't so tall.

2025-01-09 21:46 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +    background-color: rgb(32 34 48);
Add width: 23.25rem up here (and you'll remove min-width at line 140).

2025-01-09 21:47 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-width: 23.25rem;
Remove "min-width" here because you're adding "width" to line 8 instead.

2025-01-09 23:48 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-height: 566px;
done

2025-01-09 23:48 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +        padding: 5px;
done

2025-01-09 23:49 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-height: 566px;
done

2025-01-09 23:49 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +    background-color: rgb(32 34 48);
done

2025-01-09 23:49 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +        min-width: 23.25rem;
done

2025-01-10 02:42 UTC, neetunegi commented
can we please squash all the commits to one , when it is good to merge? otherwise i can do it from command line. Please let me know

2025-01-10 12:58 UTC, helms-charity requested changes
These final changes should make the cards look nearly identical to the originals.

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +    background-color: rgb(32 34 48);
It needs to be width: 23.25rem (you made it 21.45).

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +.offer-cards-content .sub-headline p {
add li in here at line 80:
```
.offer-cards-content .sub-headline p,
.offer-cards-content .sub-headline li  {
```

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        content: '\2713\00a0';
add after line 178
```
padding-right: 8px;
padding-top: 3px;
```

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        list-style: none;
add after line 174:
`padding-inline-start: 0;`

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +
Add a new style for the li here
```
.offer-cards.block ul li {
display: flex;
}
```

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        padding: 35px 20px;
Change to
`padding: 35px 20px 16px 20px;`

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +
add a new style after line 120:
```
.offer-cards-content .badge p {
margin: 0;
}
```

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +    padding: 0 7px;
Change line 110 to:
`padding: 0.25rem 0.5rem;`

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +        padding: 5px;
Change from padding to margin so that the hover effect doesn't show a white strip:
`margin: 5px`

2025-01-10 12:58 UTC, helms-charity commented on aemedge/blocks/offer-cards/offer-cards.css
> +
Can you add the hover style for this:

.offer-cards.block:hover {
    transition: box-shadow 200ms;
    box-shadow: rgba(7, 7, 11, 0.4) 4px 36px 48px -12px;
}

2025-01-10 18:42 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +        padding: 35px 20px;
added  padding: 35px 20px 16px; es lint was complainin for duplicate value at the end. tested and verified

2025-01-10 18:44 UTC, neetunegi commented on aemedge/blocks/offer-cards/offer-cards.css
> +
added box-shadow: rgba(7 7 11 / 40%) 4px 36px 48px -12px;  . specified in % accroding to new 
guideines. please let me know

2025-01-10 22:07 UTC, merged